flags:
  stunts-cartography:
    repldump2carto: true
packages:
- '.'
- location:
    git: https://github.com/HeinrichApfelmus/threepenny-gui
    commit: edeceee8f6891bffd0d92078efd581a7a4123fb4
  extra-dep: true
extra-deps:
- parsec-permutation-0.1.2.0
resolver: lts-8.2
