flags:
  stunts-cartography:
    repldump2carto: true
packages:
- '.'
- location:
    git: https://github.com/duplode/threepenny-gui
    commit: 5e01dcf482c412258d21893ceba3714ae7e6cc51
  extra-dep: true
extra-deps:
- parsec-permutation-0.1.2.0
- websockets-snap-0.9.2.0
  #- threepenny-gui-0.6.0.6
resolver: lts-6.14
